### ISSUE TITLE
This is having issues pulling its dependency

### ISSUE THREAD

**Issue by ukenpachi** [artdarek/pusherer#8]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - artdarek/pusherer 1.0.1 requires pusher/pusher-php-server 2.1.* -> no matc
hing package found.
    - artdarek/pusherer 1.0.0 requires pusher/pusher-php-server dev-serializer -
> no matching package found.
    - Installation request for artdarek/pusherer 1.0.* -> satisfiable by artdare
k/pusherer[1.0.0, 1.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

**Comment by artdarek** [comment]
Fixed
